<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>19楼昵称</th>
        <th>工号</th>
        <th>姓名</th>
        <th>角色</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>